# ── Browser ──
browser=chrome
headless=true
implicit.wait=10
page.load.timeout=30

# ── Web App ──
base.url=https://the-internet.herokuapp.com

# ── REST API ──
api.base.url=https://petstore.swagger.io/v2
openapi.spec.path=schemas/petstore-v2.yaml

# ── REST API (JSONPlaceholder) ──
jsonplaceholder.base.url=https://jsonplaceholder.typicode.com
jsonplaceholder.spec.path=schemas/jsonplaceholder-api.yaml

# ── SOAP API ──
soap.base.url=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
soap.schema.path=schemas/countryinfo.xsd
