# ── Browser ──
browser=chrome
headless=true
implicit.wait=10
page.load.timeout=30

# ── Web App ──
base.url=https://the-internet.herokuapp.com

# ── REST API ──
api.base.url=https://petstore.swagger.io/v2
openapi.spec.path=schemas/petstore-v2.yaml

# ── SOAP API ──
soap.base.url=http://www.dneonline.com/calculator.asmx
